remote_theme: pages-themes/slate@v0.2.0
plugins:
  - jekyll-remote-theme
title: [Abhina Premachandran Bindu]
description: [Welcome to my website!I am a Data ScientistğŸ‘©ğŸ»â€ğŸ’», Astronomy EnthusiastğŸ”­ , Nature loverğŸƒ. This webpage showcases some of my projectsğŸ“š I created utilizing my data science skillsğŸ› ï¸ğŸ’ªğŸ¼ğŸ‘©ğŸ»â€ğŸ’»]
